builders:
  injectable_builder:
    import: "package:deep_injectable_generator/builder.dart"
    builder_factories: ["injectableBuilder"]
    build_extensions: { ".dart": [".injectable.json"] }
    auto_apply: dependents
    runs_before: ["deep_injectable_generator|injectable_config_builder"]
    build_to: cache
  injectable_config_builder:
    import: "package:deep_injectable_generator/builder.dart"
    builder_factories: ["injectableConfigBuilder"]
    build_extensions: { ".dart": [".config.dart",".module.dart"] }
    auto_apply: dependents
    build_to: source
