name: deep_injectable_generator
description: Injectable is a convenient code generator for get_it. Inspired by Angular DI, Guice DI and inject.dart.
publish_to: none

environment:
  sdk: ">=3.0.0<4.0.0"

dependencies:
  build: ^2.1.0
  source_gen: ^1.2.7
  path: ^1.8.0
  glob: ^2.0.1
  analyzer: ">=6.4.1 <7.0.0"
  code_builder: ^4.10.0
  dart_style: ^2.0.3
  injectable: 2.3.2
  deep_injectable:
    path: ../deep_injectable
#    git:
#      url: https://github.com/tomeko-atmoapps-com/deep_injectable/
#      path: deep_injectable

  collection: ^1.17.1
  recase: ^4.1.0
  meta: ">=1.12.0"
dev_dependencies:
  build_runner: ^2.3.3
  build_test: ^2.1.3
  test: ^1.17.12
  lints: ^2.0.0
